### ISSUE TITLE
Не работает режим таймера на ESP8622

### ISSUE THREAD

**Issue by n0t-amused** [GyverLibs/TimerMs#1]
Привет! 
Пытаюсь завести на WeMos D1 Mini. Рабаотает в режиме периода, но не работает в режиме таймера. Сначала ловил тараканов у себя в коде, в итоге проверил голую демку, а она не работает:

```
#include <TimerMs.h>
TimerMs wiperReset;

void setup() {
Serial.begin(115200);
wiperReset.setTimerMode();
wiperReset.setTime(5000);
}

void loop() {
wiperReset.start();
if (wiperReset.tick()) {
  Serial.println("TICK");
}
}
```

**Comment by GyverLibs** [comment]
Привет, всё работает ровно как запрограммировано: в начале каждой итерации loop() таймер перезапускается.

**Comment by n0t-amused** [comment]
Действительно. Нужно больше спать, наверное ))

Спасибо!
