### ISSUE TITLE
Трудности использования millis() для подключения Wi-Fi

### ISSUE THREAD

**Issue by brightproject** [GyverLibs/TimerMs#3]
Заголовок немного корявый, но смысл ниже.
Когда работаешь с wifi на esp8266 то для подключения к сети, используется конструкция
```
  while (WiFi.status() != WL_CONNECTED) {
      delay(1000);
      Serial.print(".");
  }
```
То есть пока условие WL_CONNECTED не true, то в порт рисуются точки, с периодом 1 секунда.
Пробую заменить delay(); на millis();
```
  while (WiFi.status() != WL_CONNECTED) {
    if (millis() - tmr >= 1000) {
      //delay(1000);
      Serial.print(".");
      tmr = millis();
    }
  }
```
И вижу, что в случае использования delay(); с периодом 1 секунда, подключение к сети wifi происходит через 3 попытки.
В случае же использования millis(); происходят чудеса.
Во первых с периодом 1 секунда подключение к сети wifi происходит через 20-30 попыток.
Если увеличить период до 1500 например, то esp8266 вообще перезагружается.
Удалось подключать к wifi esp8266 с периодом 200 мс но через 5-10 попыток.
Что делаю не так, или библиотека "ESP8266WiFi.h" не предполагает использование иного способа "разнести" время подключений, кроме delay? 
https://github.com/esp8266/Arduino/blob/master/libraries/ESP8266WiFi/src/ESP8266WiFiSTA.cpp

**Comment by GyverLibs** [comment]
Читать документацию на 8266. Есп не должна висеть в "глухом" цикле дольше нескольких миллисекунд. Если такие конструкции необходимы - нужно вызывать yield(). Либо оставить delay(), в данном случае менять его на миллис смысла особо нет

**Comment by brightproject** [comment]
> Читать документацию на 8266. Есп не должна висеть в "глухом" цикле дольше нескольких миллисекунд. Если такие конструкции необходимы - нужно вызывать yield(). Либо оставить delay(), в данном случае менять его на миллис смысла особо нет

Можно бороться с переполнением millis через 49 дней используя переменную?
static unsigned long вместо static uint32_t

**Comment by GyverLibs** [comment]
unsigned long это и есть uint32_t, см. базовые уроки

**Comment by brightproject** [comment]
> unsigned long это и есть uint32_t, см. базовые уроки

Да, это синонимы, только в примерах где борются с переполнением millis, преимущественно применяется unsigned long.
С ваших же слов, способа борьбы с переполнением millis нет?

**Comment by GyverLibs** [comment]
> в примерах где борются с переполнением millis

боже, этому целые примеры посвящены?))

> преимущественно применяется unsigned long

Ну любят люди больше буков кода писать, что поделать 

> способа борьбы с переполнением millis нет

Проблемы с переполнением миллис нет и никогда не было, если использовать конструкцию `millis() - timer >= period`. Подробнее можно почитать в уроке https://alexgyver.ru/lessons/how-to-sketch/
