### ISSUE TITLE
Вопрос зачем сделан метод ready

### ISSUE THREAD

**Issue by THEb0nny** [GyverLibs/TimerMs#4]
Я нифига не понял зачем использовать метод ready, если обязательно нужно использовать tick, который тоже возвращает true при срабатывании. Можно объяснить этот вопрос?
Примеров очень мало, не понятны сценарии использования.

**Comment by GyverLibs** [comment]
для большей читаемости кода и по аналогии с остальными библиотеками, где есть tick(). Внутри тикера находится вся логика работы таймера, а ready() сигналит о срабатывании. Но тик тоже возвращает результат, это фича
