### ISSUE TITLE
not work if install from library manager

### ISSUE THREAD

**Issue by zappbrannigan34** [GyverLibs/TimerMs#5]
location of .h file inside src directory.
Compilation error: TimerMs.h: No such file or directory
move .h file upper

**Comment by GyverLibs** [comment]
U are doing smth wrong
![image](https://user-images.githubusercontent.com/84599917/212661063-4fdc866c-83ff-4bed-9700-c32e1f98011a.png)

**Comment by zappbrannigan34** [comment]
Using board 'nano' from platform in folder: C:\Users\zap\AppData\Local\Arduino15\packages\arduino\hardware\avr\1.8.6
Using core 'arduino' from platform in folder: C:\Users\zap\AppData\Local\Arduino15\packages\arduino\hardware\avr\1.8.6
Detecting libraries used...
"C:\\Users\\zap\\AppData\\Local\\Arduino15\\packages\\arduino\\tools\\avr-gcc\\7.3.0-atmel3.6.1-arduino7/bin/avr-g++" -c -g -Os -w -std=gnu++11 -fpermissive -fno-exceptions -ffunction-sections -fdata-sections -fno-threadsafe-statics -Wno-error=narrowing -flto -w -x c++ -E -CC -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=10607 -DARDUINO_AVR_NANO -DARDUINO_ARCH_AVR "-IC:\\Users\\zap\\AppData\\Local\\Arduino15\\packages\\arduino\\hardware\\avr\\1.8.6\\cores\\arduino" "-IC:\\Users\\zap\\AppData\\Local\\Arduino15\\packages\\arduino\\hardware\\avr\\1.8.6\\variants\\eightanaloginputs" "C:\\Users\\zap\\AppData\\Local\\Temp\\arduino-sketch-39C2415582801790905D58028AED1B40\\sketch\\water.ino.cpp" -o nul
Alternatives for TimerMs.h: [TimerMs@1.2]
ResolveLibrary(TimerMs.h)
  -> candidates: [TimerMs@1.2]
"C:\\Users\\zap\\AppData\\Local\\Arduino15\\packages\\arduino\\tools\\avr-gcc\\7.3.0-atmel3.6.1-arduino7/bin/avr-g++" -c -g -Os -w -std=gnu++11 -fpermissive -fno-exceptions -ffunction-sections -fdata-sections -fno-threadsafe-statics -Wno-error=narrowing -flto -w -x c++ -E -CC -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=10607 -DARDUINO_AVR_NANO -DARDUINO_ARCH_AVR "-IC:\\Users\\zap\\AppData\\Local\\Arduino15\\packages\\arduino\\hardware\\avr\\1.8.6\\cores\\arduino" "-IC:\\Users\\zap\\AppData\\Local\\Arduino15\\packages\\arduino\\hardware\\avr\\1.8.6\\variants\\eightanaloginputs" "-IC:\\Users\\zap\\OneDrive\\Документы\\Arduino\\libraries\\TimerMs\\src" "C:\\Users\\zap\\AppData\\Local\\Temp\\arduino-sketch-39C2415582801790905D58028AED1B40\\sketch\\water.ino.cpp" -o nul
C:\Users\zap\OneDrive\Документы\Arduino\water\water.ino:1:10: fatal error: TimerMs.h: No such file or directory
compilation terminated.
Alternatives for TimerMs.h: [TimerMs@1.2]
ResolveLibrary(TimerMs.h)
  -> candidates: [TimerMs@1.2]

Используем библиотеку TimerMs версии 1.2 из папки: C:\Users\zap\OneDrive\Документы\Arduino\libraries\TimerMs 
exit status 1

Compilation error: TimerMs.h: No such file or directory

**Comment by zappbrannigan34** [comment]
![image](https://user-images.githubusercontent.com/25005152/212662899-97000014-f568-453b-8220-ab8dd4abc114.png)

**Comment by GyverLibs** [comment]
IDE v2 is a bunch of bugs now, use IDE v1.8.19

**Comment by GyverLibs** [comment]
![image](https://user-images.githubusercontent.com/84599917/212663373-3ed05ec4-f8a6-4875-b13e-f7856ae7d692.png)

**Comment by zappbrannigan34** [comment]
![image](https://user-images.githubusercontent.com/25005152/212663968-bf87fe5d-7af7-44fd-b16f-1cd770f204a1.png)

**Comment by GyverLibs** [comment]
🤷‍♂️

**Comment by zappbrannigan34** [comment]
как отдебажить?

**Comment by zappbrannigan34** [comment]
остальные библиотеки работают

**Comment by GyverLibs** [comment]
включить подробный вывод компиляции в настройках IDE попробовать

**Comment by zappbrannigan34** [comment]
это и есть подробный вывод на скрине

**Comment by GyverLibs** [comment]
если пример из библиотеки открыть, скомпилит?
