### ISSUE TITLE
timeLeft() возвращает статичное значение

### ISSUE THREAD

**Issue by andebugan** [GyverLibs/TimerMs#8]
Функция timeLeft() всегда возвращает одно и то же значение, равное значению периода. Судя по коду оно не обновляется динамически, если не вызывается функция tick(), в которой происходит пересчёт буфера. По-хорошему надо либо указать, что для корректного использования необходимо вызывать функцию tick(), либо пересчитывать буфер при вызове функции.

**Comment by GyverLibs** [comment]
подразумевается что tick всегда вызывается
